export enum ModalName {
  Categories = "Categories",
  SwitchRole = "SwitchRole",
  DeleteUser = "DeleteUser",
  CreateCategory = "CreateCategory",
  ContentSuccess = "ContentSuccess",
  NewsletterSuccess = "NewsletterSuccess",
  NewsletterError = "NewsletterError",
  ErrorModal = "ErrorModal",
  SuccessModal = "SuccessModal",
  BanModal = "BanModal",
  CreateDiscussion = "CreateDiscussion",
  CreateThread = "CreateThread",
  AuthModal = "AuthModal",
}
