name: Vercel Production Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Add Cloudinary Secrets to Vercel
        run: |
          echo ${{ secrets.CLOUDINARY_API_KEY }} | vercel env add CLOUDINARY_API_KEY production --token ${{ secrets.VERCEL_TOKEN }}
          echo ${{ secrets.CLOUDINARY_API_SECRET }} | vercel env add CLOUDINARY_API_SECRET production --token ${{ secrets.VERCEL_TOKEN }}
          echo ${{ secrets.CLOUDINARY_CLOUD_NAME }} | vercel env add CLOUDINARY_CLOUD_NAME production --token ${{ secrets.VERCEL_TOKEN }}
          echo ${{ secrets.CLOUDINARY_URL }} | vercel env add CLOUDINARY_URL production --token ${{ secrets.VERCEL_TOKEN }}
          echo "https://usmle-bros-test.vercel.app" | vercel env add API_URL production --token ${{ secrets.VERCEL_TOKEN }}

      - name: Add Firebase Secrets to Vercel
        run: |
          echo ${{ secrets.FIREBASE_PRIVATE_KEY }} | base64 --decode | sed 's/\\n/\n/g' | vercel env add FIREBASE_PRIVATE_KEY production --token ${{ secrets.VERCEL_TOKEN }}
          echo ${{ secrets.FIREBASE_PROJECT_ID }} | vercel env add FIREBASE_PROJECT_ID production --token ${{ secrets.VERCEL_TOKEN }}
          echo ${{ secrets.FIREBASE_SERVICE_ACCOUNT }} | vercel env add FIREBASE_SERVICE_ACCOUNT production --token ${{ secrets.VERCEL_TOKEN }}

      - name: Add Other Secrets to Vercel
        run: |
          echo ${{ secrets.FIREBASE_API_KEY }} | vercel env add FIREBASE_API_KEY production --token ${{ secrets.VERCEL_TOKEN }}
          echo ${{ secrets.FIREBASE_AUTH_DOMAIN }} | vercel env add FIREBASE_AUTH_DOMAIN production --token ${{ secrets.VERCEL_TOKEN }}
          echo ${{ secrets.FIREBASE_STORAGE_BUCKET }} | vercel env add FIREBASE_STORAGE_BUCKET production --token ${{ secrets.VERCEL_TOKEN }}
          echo ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }} | vercel env add FIREBASE_MESSAGING_SENDER_ID production --token ${{ secrets.VERCEL_TOKEN }}
          echo ${{ secrets.FIREBASE_APP_ID }} | vercel env add FIREBASE_APP_ID production --token ${{ secrets.VERCEL_TOKEN }}
          echo ${{ secrets.FIREBASE_MEASUREMENT_ID }} | vercel env add FIREBASE_MEASUREMENT_ID production --token ${{ secrets.VERCEL_TOKEN }}
          echo ${{ secrets.GOOGLE_ADSENSE_CLIENT }} | vercel env add GOOGLE_ADSENSE_CLIENT production --token ${{ secrets.VERCEL_TOKEN }}
          echo ${{ secrets.DATA_AD_SLOT_DISPLAY_AD }} | vercel env add DATA_AD_SLOT_DISPLAY_AD production --token ${{ secrets.VERCEL_TOKEN }}

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=Production --token=${{ secrets.VERCEL_TOKEN }} && cat .vercel/.env.production.local

      - name: Install Dependencies and Build
        run: |
          npm install --global vercel@latest
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

    environment:
      name: Vercel Actions Production Deployment
      url: ${{ job.status == 'success' && steps.deploy.outputs.url }}
